apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    app: redis
    project: roboshop
    tier: db
  clusterIP: None
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379

