
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  labels: # these labels are deployment labels
    app: redis
    project: roboshop
    tier: db
spec:
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels: # these labels are used to find the pods
      app: redis
      project: roboshop
      tier: db
  serviceName: "redis"
  template:
    metadata:
      labels: # these labels are pod labels
        app: redis
        project: roboshop
        tier: db
    spec:
      containers:
      - name: redis
        image: redis
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: redis
        volumeMount:
        - name: redis
          mountPath: /data
  volumeClaimTemplate:
  - metadata: 
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi



